# Generated by Django 2.2.2 on 2019-07-18 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20190701_1708'),
        ('event_registrations', '0010_remove_teammember_invitation_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_team_registration', models.BooleanField(default=False)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('request_checksum', models.CharField(max_length=200)),
                ('response_checksum', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Failed', 'Failed'), ('Successful', 'Successful')], max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.Profile')),
                ('solo_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='event_registrations.SoloEventRegistration')),
                ('team_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='event_registrations.TeamEventRegistration')),
            ],
        ),
    ]
