# Generated by Django 2.2.2 on 2019-07-01 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190629_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Indian Institute of Information Technology, Sri City', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='college_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Institute'),
        ),
    ]
