# Generated by Django 2.2.2 on 2019-07-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190701_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(default='Indian Institute of Information Technology, Sri City', max_length=200, unique=True),
        ),
    ]
