# Generated by Django 2.2.2 on 2019-06-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190617_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='public_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
