# Generated by Django 2.2.2 on 2019-06-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registrations', '0003_auto_20190627_0920'),
        ('events', '0002_remove_event_participants_waiting_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants_waiting_list',
            field=models.ManyToManyField(related_name='waiting_list_events', to='event_registrations.Team'),
        ),
    ]
