# Generated by Django 2.2.2 on 2019-06-22 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190617_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='event_logo',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_picture',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='event',
            name='max_team_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='min_participants',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='event',
            name='min_team_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(related_name='events', to='events.Category'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='participated_events', to='events.Team'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants_waiting_list',
            field=models.ManyToManyField(related_name='waiting_list_events', to='events.Team'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(related_name='events', to='events.Tags'),
        ),
    ]
