# Generated by Django 2.2.2 on 2019-07-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_participants_waiting_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='reserved_fee',
            field=models.IntegerField(default=0),
        ),
    ]
