# Generated by Django 2.2.2 on 2019-06-22 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190622_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoloEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.Event')),
            ],
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='TeamEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.Event')),
                ('min_team_size', models.IntegerField(default=1)),
                ('max_team_size', models.IntegerField(default=1)),
            ],
            bases=('events.event',),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='event',
            name='reserved_slots',
            field=models.IntegerField(default=0, help_text='No of participant slots reserved for external players'),
        ),
    ]
