# Generated by Django 2.2.2 on 2019-06-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20190628_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
