# Generated by Django 2.2.2 on 2019-06-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcomment',
            name='posting_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
