# Generated by Django 2.2.2 on 2019-06-22 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_profileparticipant_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, max_length=20, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_accepted', models.BooleanField(default=False, help_text='If true, person has accepted invitation and is part of the team')),
                ('joined_on', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Profile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_registrations.Team')),
            ],
        ),
    ]
