# Generated by Django 2.2.2 on 2019-07-11 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, max_length=20, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_accepted', models.BooleanField(default=False, help_text='If true, person has accepted invitation and is part of the team')),
                ('joined_on', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Profile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_registrations.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamEventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, max_length=100, unique=True)),
                ('is_complete', models.BooleanField(default=False, help_text='Tells whether the team has completed all formalities like payments etc.')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Tells whether registration is confirmed or is in waiting')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_registrations.Team')),
            ],
        ),
        migrations.CreateModel(
            name='SoloEventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, max_length=100, unique=True)),
                ('is_complete', models.BooleanField(default=False, help_text='Tells whether user has completed all formalities like payments etc.')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Tells whether registration is confirmed or is in waiting')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Event')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
