# Generated by Django 2.2.2 on 2019-06-28 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('event_registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, max_length=100, unique=True)),
                ('is_complete', models.BooleanField(default=False, help_text='Tells whether the team has completed all formalities like payments etc.')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Tells whether registration is confirmed or is in waiting')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_registrations.Team')),
            ],
        ),
    ]
