# Generated by Django 2.2.2 on 2019-06-27 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_registrations', '0002_auto_20190626_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammember_set', to='event_registrations.Team'),
        ),
    ]
