# Generated by Django 2.2.2 on 2019-06-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registrations', '0004_auto_20190627_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teameventregistration',
            name='is_complete',
            field=models.BooleanField(default=False, help_text='Tells whether a team has completed all formalities like payments etc.'),
        ),
    ]
