# Generated by Django 2.2.2 on 2019-07-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registrations', '0007_auto_20190629_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='teameventregistration',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
