# Generated by Django 2.2.2 on 2019-07-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registrations', '0008_teameventregistration_is_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='soloeventregistration',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
