# Generated by Django 2.2.2 on 2019-07-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_registrations', '0009_soloeventregistration_is_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='invitation_rejected',
        ),
    ]
