# Generated by Django 2.2.2 on 2019-07-09 05:35

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
                ('upload_path', models.CharField(max_length=250)),
                ('forced_filename', models.CharField(blank=True, max_length=80, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('uploaded_image', models.ImageField(upload_to=base.models.set_file_upload_path)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
