# Generated by Django 2.2.2 on 2019-07-09 07:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_imageuploadmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadmodel',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 7, 9, 7, 13, 3, 853603, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageuploadmodel',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 7, 9, 7, 13, 30, 109515, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
